# Generated by Django 3.0.5 on 2021-01-19 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='yamdbuser',
            name='activation_code',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
