# Generated by Django 3.1.5 on 2021-01-20 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yamdbuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='yamdbuser',
            name='username',
            field=models.CharField(max_length=40),
        ),
    ]
