# Generated by Django 3.0.5 on 2021-01-13 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('usr', 'user'), ('mdr', 'moderator'), ('adm', 'admin')], default=('usr', 'user'), max_length=3),
        ),
        migrations.AlterField(
            model_name='yamdbuser',
            name='role',
            field=models.ForeignKey(default=('usr', 'user'), on_delete=django.db.models.deletion.SET_DEFAULT, to='users_api.Role'),
        ),
    ]
