# Generated by Django 3.0.5 on 2021-01-15 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='yamdbuser',
            options={'ordering': ('-id',)},
        ),
    ]
