# Generated by Django 3.0.5 on 2021-01-13 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0002_auto_20210114_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yamdbuser',
            name='bio',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
