# Generated by Django 3.1.5 on 2021-01-21 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0002_auto_20210120_1553'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='yamdbuser',
            options={'ordering': ('-id',), 'verbose_name': 'Yamdb User', 'verbose_name_plural': 'Yamdb Users'},
        ),
        migrations.AlterField(
            model_name='yamdbuser',
            name='bio',
            field=models.TextField(blank=True, max_length=255, verbose_name='Users biography'),
        ),
    ]
