# Generated by Django 3.0.5 on 2021-01-14 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0003_auto_20210114_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yamdbuser',
            name='role',
            field=models.CharField(choices=[('usr', 'user'), ('mdr', 'moderator'), ('adm', 'admin')], default=('usr', 'user'), max_length=3),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
