# Generated by Django 3.0.5 on 2021-01-17 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('title_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='genre',
            field=models.ManyToManyField(blank=True, related_name='titles', to='title_api.Genre'),
        ),
    ]
