# Generated by Django 3.0.5 on 2021-01-14 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('title_api', '0003_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Category',
                'ordering': ['name'],
            },
        ),
    ]
