# Generated by Django 3.1.5 on 2021-01-22 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('title_api', '0003_auto_20210121_1939'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='category',
            name='unique_category',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Category name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='Category slug'),
        ),
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='title_api.title'),
        ),
    ]
