# Generated by Django 3.0.5 on 2021-01-17 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('title_api', '0004_auto_20210117_1553'),
        ('title_api', '0004_auto_20210117_1554'),
    ]

    operations = [
    ]
