# Generated by Django 3.0.5 on 2021-01-15 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('title_api', '0005_auto_20210114_2213'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
        ),
    ]
