# Generated by Django 3.0.5 on 2021-01-15 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('title_api', '0006_genre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['name']},
        ),
    ]
