# Generated by Django 3.0.5 on 2021-01-15 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('title_api', '0007_auto_20210115_1354'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='title',
            options={'ordering': ['genre', 'name', 'year']},
        ),
    ]
