# Generated by Django 3.0.5 on 2021-01-15 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('title_api', '0008_auto_20210115_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='slug',
            field=models.SlugField(default='def_slug', unique=True),
            preserve_default=False,
        ),
    ]
