# Generated by Django 3.0.5 on 2021-01-18 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('title_api', '0009_auto_20210119_0018'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
    ]
