# Generated by Django 3.0.5 on 2021-01-19 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('title_api', '0011_auto_20210119_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
