# Generated by Django 3.0.5 on 2021-01-19 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('title_api', '0012_auto_20210119_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=80),
        ),
    ]
