# Generated by Django 3.0.5 on 2021-01-15 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('title_api', '0012_auto_20210115_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
