# Generated by Django 3.0.5 on 2021-01-19 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('title_api', '0013_auto_20210119_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='genre',
            field=models.ManyToManyField(related_name='titles', to='title_api.Genre'),
        ),
    ]
