# Generated by Django 3.0.5 on 2021-01-15 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('title_api', '0013_auto_20210115_2307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='title',
            old_name='categories',
            new_name='category',
        ),
    ]
