# Generated by Django 3.0.5 on 2021-01-15 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('title_api', '0014_auto_20210115_2310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
