# Generated by Django 3.0.5 on 2021-01-15 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('title_api', '0015_remove_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
