# Generated by Django 3.0.5 on 2021-01-15 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('title_api', '0017_auto_20210115_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
