# Generated by Django 3.0.5 on 2021-01-15 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('title_api', '0018_auto_20210115_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='slug',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
