# Generated by Django 3.0.5 on 2021-01-15 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('title_api', '0020_auto_20210115_2358'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('slug', 'name'), name='unique_category'),
        ),
    ]
