# Generated by Django 3.0.5 on 2021-01-16 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('title_api', '0021_auto_20210116_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
