# Generated by Django 3.0.5 on 2021-01-16 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('title_api', '0026_auto_20210116_1518'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
    ]
